[package]
name = "cosmwasm-ext"
version = "0.14.0-beta1"
authors = ["shiki.tak"]
edition = "2018"
description = "Bindings for CosmWasm contracts to call into custom modules of Link Core"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { path = "../std", version = "0.14.0-beta1" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0"

[dev-dependencies]
cosmwasm-schema = { path = "../schema" }
